config/routes.rb
Rails.application.routes.draw do
  root 'offers#index'

  match '/auth/:provider/callback', to: 'sessions#create', via: [ :get, :post ]
  get '/logout', to: 'sessions#destroy'
  get '/login', to: redirect('/auth/facebook')

  resources :offers

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/house.rb
class House < ActiveRecord::Base
  to_param :address

  has_many :offers, dependent: :destroy

  validates :address, presence: true
  validates :address, uniqueness: { case_sensitive: false }
end

app/models/offer.rb
class Offer < ActiveRecord::Base
  belongs_to :house, counter_cache: true, touch: true
  belongs_to :user

  validates :reason, presence: true
  validates :offered_at, presence: true
  validates :replied_at, presence: true
  validates :amount, numericality: { greater_than: 0 }
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :offers, dependent: :destroy

  class Name
    attr_reader :first, :last

    def initialize(user)
      @first, @last = user.first_name, user.last_name
    end

    def full
      "#{ first } #{ last }"
    end

    def short
      "#{ first } #{ last[0] }."
    end
  end

  def name
    @name ||= Name.new(self)
  end

  def self.from_omniauth(auth)
    key   = auth.slice(:provider, :uid)
    attrs = auth[:info].slice(:email, :first_name, :last_name, :image)

    find_or_initialize_by(key).tap do |user|
      user.update! attrs
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  include Authenticatable
end

app/controllers/concerns/authenticatable.rb
module Authenticatable
  extend ActiveSupport::Concern

  included do
    helper_method :current_user
    helper_method :logged_in?
  end

  def authenticate!
    redirect_to login_path unless logged_in?
  end

  def current_user
    @current_user ||= if id = session[:user] then User.find_by id: id end
  end

  def current_user=(user)
    @current_user = user
    session[:user] = user.to_param
  end

  def logged_in?
    current_user != nil
  end
end

app/controllers/offers_controller.rb
class OffersController < ApplicationController
  respond_to :html

  before_action :authenticate!, except: [ :index ]

  def index
    skope = logged_in? ? House.includes(offers: :user) : House.all
    @houses = skope.where.not(offers_count: 0).order(updated_at: :desc)
  end

  def new
    @offer = current_user.offers.build
    @house = @offer.build_house
  end

  def create
    @house = House.create house_params
    @offer = current_user.offers.build offer_params
    @offer.house = @house
    @offer.save
    respond_with @offer
  end

  private

    def house_params
      params.require(:house).permit(:address)
    end

    def offer_params
      params.require(:offer).permit(:amount, :offered_at, :replied_at, :reason)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_filter :verify_authenticity_token

  def create
    self.current_user = User.from_omniauth auth_params
    redirect_to root_path, notice: 'Successfully logged in!'
  end

  def destroy
    reset_session
    redirect_to root_path, notice: 'You have logged out.'
  end

  private
    def auth_params
      ActionController::Parameters.new( env['omniauth.auth'] ).permit!
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/houses/_house.html.erb
<%= div_for house do %>
  <p class="address">
    <%= house.address %>
  </p>

  <dl>
    <dt>Added</dt>
    <dd><%= time_ago_in_words house.created_at %> ago</dd>
    <dt>Activity</dt>
    <dd><%= time_ago_in_words house.updated_at %> ago</dd>
    <dt>Offers</dt>
    <dd><%= house.offers.size %></dd>
  </dl>

  <% if logged_in? %>
    <ul>
      <%= render house.offers %>
    </ul>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AbleBuyer</title>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if logged_in? %>
  <div>
    <%= image_tag current_user.image, size: '32x32' %>
    Welcome back, <%= current_user.first_name %>

    <div style="float:right;">
      <%= link_to 'submit your story', new_offer_path %> |
      <%= link_to 'logout', logout_path %>
    </div>
  </div>
<% else %>
  <%= link_to image_tag('facebook/active_600.png'), login_path %>
<% end %>

<%= yield %>

</body>
</html>

app/views/offers/_form.html.erb
<%= form_for @offer do |f| %>
  <fieldset>
    <legend>House (required)</legend>

    <%= render partial: 'shared/error_messages', object: @house %>

    <%= fields_for @house do |h| %>
      <%= h.label :address %>
      <%= h.text_area :address %>
    <% end %>
  </fieldset>

  <fieldset>
    <legend>Offer (required)</legend>

    <%= render partial: 'shared/error_messages', object: @offer %>

    <div>
      <%= f.label :amount %>
      <%= f.number_field :amount %>
    </div>

    <div>
      <%= f.label :offered_at %>
      <%= f.date_select :offered_at, order: [ :month, :day, :year ],
        include_blank: true, end_year: Time.current.year %>
    </div>

    <div>
      <%= f.label :replied_at %>
      <%= f.date_select :replied_at, order: [ :month, :day, :year ],
        include_blank: true, end_year: Time.current.year %>
    </div>

    <div>
      <%= f.label :reason %>
      <%= f.text_area :reason %>
    </div>
  </fieldset>

  <fieldset>
    <legend>Offer (optional)</legend>

    <div>
      <%= f.label :mls %>
      <%= f.text_field :mls %>
    </div>

    <div>
      <%= f.label :agent %>
      <%= f.text_field :agent %>
    </div>
  </fieldset>

  <div>
    <%= f.submit %>
  </div>
<% end %>

app/views/offers/_offer.html.erb
<li class="offer">
  <div>
    From <%= offer.user.name.short %>,
    <%= time_ago_in_words offer.created_at %> ago
  </div>

  <div>
    MLS # <%= offer.mls.present? ? offer.mls : 'n/a' %><br />
    Agent <%= offer.agent.present? ? offer.agent : 'n/a' %>
  </div>

  <div>
    Amount <%= number_to_currency offer.amount %>,
    <%= time_ago_in_words offer.offered_at %> ago
  </div>

  <div>
    Replied <%= time_ago_in_words offer.replied_at %> ago
  </div>

  <blockquote>
    <%= offer.reason %>
  </blockquote>
</li>

app/views/offers/index.html.erb
<%= render @houses %>

app/views/offers/new.html.erb
<h2>New Offer</h2>

<%= render 'form' %>

app/views/shared/_error_messages.html.erb
<% if error_messages.errors.any? %>
  <div class="error_explanation">
    <h2>
      <%= pluralize error_messages.errors.count, "error" %>
      prohibited this house from being saved:
    </h2>

    <ul>
      <% error_messages.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>